spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    ws-consumer:
      group-id: ws-group
    history-consumer:
      group-id: history-group
