apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: wwweb:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  selector:
    app: www
  ports:
    - port: 5173
      targetPort: 5173
  type: LoadBalancer