# Common properties used by all profiles
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  kafka:
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        session.timeout.ms: 1000
        heartbeat.interval.ms: 500
    ws-consumer:
      group-id: ws-group
    history-consumer:
      group-id: history-group

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/wwire
    username: wwire
    password: admin
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: cp-kafka:9092
  datasource:
    url: jdbc:postgresql://db:5432/wwire
    username: wwire
    password: admin
    driver-class-name: org.postgresql.Driver