spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      enable-auto-commit: true
    ws-consumer:
      group-id: ws-group
    history-consumer:
      group-id: history-group
  datasource:
    url: jdbc:postgresql://localhost:5432/wwire
    username: wwire
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
