spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        session.timeout.ms: 1000
        heartbeat.interval.ms: 500
    ws-consumer:
      group-id: ws-group
    history-consumer:
      group-id: history-group
  datasource:
    url: jdbc:postgresql://localhost:5432/wwire
    username: wwire
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate  # use validate with Flyway
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false  # disable OSIV
