version: '3.8'
services:
  www:
    image: wwweb:latest
    build:
      context: ../ww-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
  api:
    image: wwapi:latest
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - cp-kafka
      - db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    stop_grace_period: 4s
    container_name: zookeeper
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 500
      ZOOKEEPER_SESSION_TIMEOUT: 1500
  cp-kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: cp-kafka
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLUSTER_ID: "random-cluster-id"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 1000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 2000
  db:
    image: postgres:17-alpine
    depends_on:
      - cp-kafka
      - zookeeper
    restart: always
    environment:
      POSTGRES_USER: wwire
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  pgdata: